"""
Usage:
# Create train data:
python xml_to_csv.py -i [PATH_TO_IMAGES_FOLDER]/train -o [PATH_TO_ANNOTATIONS_FOLDER]/train_labels.csv

# Create test data:
python xml_to_csv.py -i [PATH_TO_IMAGES_FOLDER]/test -o [PATH_TO_ANNOTATIONS_FOLDER]/test_labels.csv
"""

import os
import glob
import pandas as pd
from pathlib import Path
import argparse
import xml.etree.ElementTree as ET


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines them in a single Pandas datagrame.

    Parameters:
    ----------
    path : {str3
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """
    xml_list = []
    xml_files = Path(path).glob('*.xml')
    for xml_file in xml_files:
        image_file = xml_file.parent/f'{xml_file.stem}.jpg'
        try:
            tree = ET.parse(str(xml_file))
        except:
            print("cannot open xml:", f'<{xml_file}>', "move to not_opened")
            not_opened = Path('not_opened')
            not_opened.mkdir(exist_ok=True)
            xml_file.replace(not_opened/xml_file)
            image_file.replace(not_opened/image_file)
            continue
        root = tree.getroot()
        for obj in root.findall('object'):
            value = (image_file.name,
                    float(root.find('size')[0].text),
                    float(root.find('size')[1].text),
                    obj[0].text,
                    float(obj[4][0].text),
                    float(obj[4][1].text),
                    float(obj[4][2].text),
                    float(obj[4][3].text)
                    )
            xml_list.append(value)
    column_name = ['filename', 'width', 'height',
                'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


def main():
    # Initiate argument parser
    parser = argparse.ArgumentParser(
        description="Sample TensorFlow XML-to-CSV converter")
    parser.add_argument("-i",
                        "--inputDir",
                        help="Path to the folder where the input .xml files are stored",
                        type=str)
    parser.add_argument("-o",
                        "--outputFile",
                        help="Name of output .csv file (including path)", type=str)
    args = parser.parse_args()

    if(args.inputDir is None):
        args.inputDir = os.getcwd()
    if(args.outputFile is None):
        args.outputFile = args.inputDir + "/labels.csv"

    assert(os.path.isdir(args.inputDir))

    xml_df = xml_to_csv(args.inputDir)
    xml_df.to_csv(
        args.outputFile, index=None)
    print('Successfully converted xml to csv.')


if __name__ == '__main__':
    main()